import './globals.css';
import type { Metadata } from 'next';
import { Nunito, Nunito_Sans } from 'next/font/google';
import clsx from 'clsx';

const nunito = Nunito({
	subsets: ['latin'],
	variable: '--font-nunito',
	preload: true,
	display: 'swap',
});
const nunito_sans = Nunito_Sans({
	subsets: ['latin'],
	variable: '--font-nunito_sans',
	preload: true,
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={clsx(nunito.variable, nunito_sans.variable)}>{children}</body>
		</html>
	);
}
